#!/bin/bash -l
# Training Script Autogenerated by UniversalScripter : https://github.com/thakkarV/UniversalScripter
# To be used for trainig WaveNet models on the BU SCC

# PROJECT NAME
#$ -P textconv

# JOB TIME
#$ -l h_rt=48:00:00

# SEND EMAIL BY DEFAULT
#$ -m beas

# JOB NAME
#$ -N LCTestTrain

# TOTAL CPU CORES
#$ -pe omp 4

# TOTAM MEMORY
#$ -l mem_total=32G

# TOTAL GPUS
#$ -l gpus=0.25

# GPU COMPUTE CAPABILITY
#$ -l gpu_c=6.0

# LOAD SOFTWARE MODULES
module load cuda/8.0
module load cudnn/6.0
module load python/2.7.13
module load tensorflow/r1.2

# EXECUTION LINE
python /projectnb/textconv/WaveNet/Ali/tensorflow-wavenet/train.py \
--data-dir=/projectnb/textconv/WaveNet/Ali/tensorflow-wavenet/wavenet \
--logdir=/projectnb/textconv/WaveNet/Models/LCWavenet/Logs \
--wavenet-params=/projectnb/textconv/WaveNet/Models/LCWavenet/lc_wavenet_params.json \
--learning-rate=0.001 \
--lc-channels=128 \
--lc-fileformat=*.mid


